---

- hosts: loadbal
  gather_facts: no
    
  #pre_tasks:
  #  
  #  - name: update apt cache
  #    apt: 
  #      update_cache: yes

  tasks:

    #- name: install haproxy
    #  package:
    #    name: haproxy
    #    state: present
    #
    #- name: append config snippet to haproxy.cfg file
    #  blockinfile:
    #    path: /etc/haproxy/haproxy.cfg
    #    backup: yes
    #    block: | 

    #      frontend kubernetes-frontend
    #          bind 172.16.16.100:6443
    #          mode tcp
    #          option tcplog
    #          default_backend kubernetes-backend

    #      backend kubernetes-backend
    #          mode tcp
    #          option tcp-check
    #          balance roundrobin
    #          server kmaster1 172.16.16.101:6443 check fall 3 rise 2
    #          server kmaster2 172.16.16.102:6443 check fall 3 rise 2

    #  notify: restart haproxy  

    - name: disable firewall
      ufw:
        state: disabled
    
    - name: disable swap if currently in use 
      shell: swapoff -a

    #- name: Remove swapfile from /etc/fstab
    #  mount:
    #    fstype: swap
    #    state: absent

    - name: disable swap entry in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    


  handlers:
    
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
