---

# execute with 'ansible-playbook --ask-pass ...'

- hosts: all
  gather_facts: no

  tasks: 
    
    - name: create .ssh directory
      file: 
        path: /root/.ssh
        state: directory
  
    - name: copy public key
      copy: 
        src: /root/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        mode: '0600'      
